services:
  db:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: simple_password
      POSTGRES_DB: dino
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pg-network

volumes:
  pgdata:

networks:
  pg-network:
    driver: bridge